[build-system]
requires = ["maturin>=1.1,<2.0"]
build-backend = "maturin"

[project]
authors = [{ name = "ppeter", email = "ppeter1@smail.uni-koeln.de" }]
name = "mcr_py"
version = "0.1.0"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "aiohttp>=3.8.6",
    "folium>=0.16.0",
    "fsspec>=2023.1.0",
    "h3>=3.7.7",
    "ipykernel>=6.16.2",
    "joblib>=1.3.2",
    "jupyter>=1.1.1",
    "maturin>=1.8.1",
    "networkx>=2.6.3",
    "notebook>=6.5.7",
    "overpy>=0.7",
    "polars>=0.18.4",
    "pyrosm>=0.6.1",
    "requests>=2.31.0",
    "shapely>=2.0.6",
    "typer>=0.15.1",
]

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
module-name = "mcr_py._mcr_py"

[tool.ruff]
extend-include = ["*.ipynb"]
